version: '3'
services:
  web:
    build:
        context: ../
        dockerfile: ./devops/Dockerfile
    image: admin-panel-${ENV}
    container_name: admin-panel-${ENV}
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
       - "${external_port}:80"
    restart: always



    # Test merge
