export const FakeEmployees = [
  {
    id: 1,
    phoneNumber: '841-68-9499',
    nameAR: 'Dawidsohn',
    email: 'mdawidsohn0@nih.gov',
    nameEN: 'Misti',
    branch: 'Meembee',
    location: 'Indonesia',
    photo: 'https://robohash.org/nesciuntaliquamaut.png?size=50x50&set=set1',
    title: 'Nurse Practicioner',
    isCasher: false,
    rate: 4.3,
  },
  {
    id: 2,
    phoneNumber: '136-60-2712',
    nameAR: 'Dominique',
    email: 'cdominique1@msu.edu',
    nameEN: 'Charlene',
    branch: 'Vimbo',
    location: 'Costa Rica',
    photo: 'https://robohash.org/iuremaximeofficia.png?size=50x50&set=set1',
    title: 'Director of Sales',
    isCasher: false,
    rate: 4.9,
  },
  {
    id: 3,
    phoneNumber: '229-22-2326',
    nameAR: 'Ragborne',
    email: 'jragborne2@flickr.com',
    nameEN: 'Jamaal',
    branch: 'Quatz',
    location: 'Albania',
    photo: 'https://robohash.org/oditsuntdelectus.png?size=50x50&set=set1',
    title: 'Research Nurse',
    isCasher: true,
    rate: 2.7,
  },
  {
    id: 4,
    phoneNumber: '406-86-7008',
    nameAR: 'Kerswell',
    email: 'jkerswell3@ifeng.com',
    nameEN: 'Juliana',
    branch: 'Zava',
    location: 'Indonesia',
    photo: 'https://robohash.org/corporismodiet.png?size=50x50&set=set1',
    title: 'Safety Technician III',
    isCasher: true,
    rate: 4.9,
  },
  {
    id: 5,
    phoneNumber: '471-43-7404',
    nameAR: 'McMurraya',
    email: 'smcmurraya4@fc2.com',
    nameEN: 'Sol',
    branch: 'Bubbletube',
    location: 'Morocco',
    photo: 'https://robohash.org/abaccusantiummodi.png?size=50x50&set=set1',
    title: 'Senior Editor',
    isCasher: true,
    rate: 3.2,
  },
  {
    id: 6,
    phoneNumber: '782-61-1149',
    nameAR: 'Shute',
    email: 'rshute5@woothemes.com',
    nameEN: 'Roxie',
    branch: 'Kanoodle',
    location: 'Czech Republic',
    photo: 'https://robohash.org/eosrerumdolore.png?size=50x50&set=set1',
    title: 'Senior Quality Engineer',
    isCasher: true,
    rate: 0.6,
  },
  {
    id: 7,
    phoneNumber: '552-15-7397',
    nameAR: 'Vokes',
    email: 'bvokes6@fda.gov',
    nameEN: 'Boyd',
    branch: 'Skyba',
    location: 'Poland',
    photo: 'https://robohash.org/recusandaesaepedolorem.png?size=50x50&set=set1',
    title: 'Senior Cost Accountant',
    isCasher: true,
    rate: 3.7,
  },
  {
    id: 8,
    phoneNumber: '217-43-2496',
    nameAR: 'Bradder',
    email: 'cbradder7@ning.com',
    nameEN: 'Clemmie',
    branch: 'Kanoodle',
    location: 'China',
    photo: 'https://robohash.org/reiciendisesseunde.png?size=50x50&set=set1',
    title: 'Staff Scientist',
    isCasher: true,
    rate: 1.6,
  },
  {
    id: 9,
    phoneNumber: '291-31-3166',
    nameAR: 'Brizland',
    email: 'gbrizland8@typepad.com',
    nameEN: 'Gayla',
    branch: 'Fivechat',
    location: 'Portugal',
    photo: 'https://robohash.org/laudantiumautdolor.png?size=50x50&set=set1',
    title: 'Registered Nurse',
    isCasher: false,
    rate: 4.9,
  },
  {
    id: 10,
    phoneNumber: '673-73-9902',
    nameAR: 'Howson',
    email: 'jhowson9@newsvine.com',
    nameEN: 'Jennette',
    branch: 'Oyonder',
    location: 'Norway',
    photo: 'https://robohash.org/velvoluptatumminima.png?size=50x50&set=set1',
    title: 'Financial Advisor',
    isCasher: false,
    rate: 2.2,
  },
  {
    id: 11,
    phoneNumber: '785-91-0194',
    nameAR: 'Menchenton',
    email: 'pmenchentona@cdbaby.com',
    nameEN: 'Patrice',
    branch: 'Brightbean',
    location: 'France',
    photo: 'https://robohash.org/veldeseruntarchitecto.png?size=50x50&set=set1',
    title: 'Community Outreach Specialist',
    isCasher: true,
    rate: 4.0,
  },
  {
    id: 12,
    phoneNumber: '199-91-4966',
    nameAR: 'Beckinsall',
    email: 'gbeckinsallb@patch.com',
    nameEN: 'Gilberta',
    branch: 'Jaxnation',
    location: 'United States',
    photo: 'https://robohash.org/remquodid.png?size=50x50&set=set1',
    title: 'Financial Advisor',
    isCasher: false,
    rate: 4.8,
  },
  {
    id: 13,
    phoneNumber: '359-45-3362',
    nameAR: 'Gaunter',
    email: 'cgaunterc@ted.com',
    nameEN: 'Carolann',
    branch: 'Wordware',
    location: 'Portugal',
    photo: 'https://robohash.org/sintdoloribuslaboriosam.png?size=50x50&set=set1',
    title: 'Staff Scientist',
    isCasher: true,
    rate: 0.8,
  },
  {
    id: 14,
    phoneNumber: '378-13-0593',
    nameAR: 'Hegdonne',
    email: 'ahegdonned@seesaa.net',
    nameEN: 'Angelita',
    branch: 'Zoomdog',
    location: 'Mauritius',
    photo: 'https://robohash.org/nostrumoditpraesentium.png?size=50x50&set=set1',
    title: 'Occupational Therapist',
    isCasher: false,
    rate: 3.6,
  },
  {
    id: 15,
    phoneNumber: '816-12-3737',
    nameAR: 'Bompas',
    email: 'wbompase@salon.com',
    nameEN: 'Winona',
    branch: 'Shuffledrive',
    location: 'Argentina',
    photo: 'https://robohash.org/doloresnumquamatque.png?size=50x50&set=set1',
    title: 'Chemical Engineer',
    isCasher: false,
    rate: 3.3,
  },
];
