export const expectedObj = {
  bookingId: 0,
  canCancel: true,
  rate: 0,
  bookingDate: '',
  customerId: 0,
  isCustomer: true,
  customerName: '',
  customerMobile: '',
  serviceProviderId: 0,
  spName: '',
  spMobile: '',
  salonStartTime: '',
  salonEndTime: '',
  serviceId: 0,
  serviceName: '',
  serviceDuration: '',
  serviceTimeSlot: {
    from: '',
    to: '',
  },
  long: 0,
  lat: 0,
  address: '',
  servicePrice: 0,
  bookingPrice: 0,
  employeeID: 0,
  employeeName: '',
  employeeIsQueue: true,
  bookingStatus: {
    id: 0,
    name: '',
  },
  queueNumber: 0,
  queueWaitingTime: '',
  queuedCustomers: 0,
  anonymousUser: {
    name: '',
    phone: '',
  },
  paymentMethodId: 0,
};
