import { servicesFakeObject } from './SelectBranchesComponents/FakeServices';
export const initalEmployeeData = {
  nameAr: '',
  nameEn: '',
  workingLocation: 2,
  branches: [],
  mobileNumber: null,
  email: null,
  isCasher: false,
  casherPin: null,
  image: null,
  staffTItleAr: null,
  staffTItleEn: null,
  notes: null,
  startWorkingDate: null,
  endWorkingDate: null,
  servicesCommission: 0,
  productsCommission: 0,
  offersCommission: 0,
};
